project:
  type: website
  output-dir: docs

website:
  title: "Vom Überleben zur Liebe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: diese-eine-sache.qmd
        text: Diese eine Sache
      - about.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

